### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by cdurcan6** [Syferus/ReturnToMoriaSaves#1]
The current state of the documentation is not meeting the needs of our users and contributors. It lacks clarity, completeness, and organization, which is hindering the overall user experience and impeding potential contributors from getting involved. In light of this, we should prioritize improving our documentation to make it more accessible and user-friendly.

**Comment by rwflan** [comment]
Ah, the sweet serenade of feedback! It’s always enlightening to learn from the discerning eyes of our users and contributors, who, with eagle-eyed precision, help us navigate the treacherous waters of documentation inadequacy. I’ve taken your heartfelt cry for clarity and organization to heart and bestowed upon our README.md file a makeover of epic proportions. Behold the Table of Contents, a magical portal to sections unheard of! Marvel at the detailed instructions that now grace our humble repository setup, branching strategy, and .gitignore configuration sections. And lo, to welcome the brave souls yearning to contribute, we now have Contribution Guidelines and a FAQs section shimmering with the glow of inclusivity.

I trust this monumental transformation addresses the cavernous void that was our previous attempt at documentation. Your insightful scrutiny has led us from the shadows of ambiguity into the blinding light of clarity and completeness. May your journey through our newly polished documentation be as exhilarating as a ride through the halls of Moria!
